### ISSUE TITLE
error - not a setting instance link to footer settings

### ISSUE THREAD

**Issue by CrymSonir** [telabotanica/moodle-theme_telaformation#13]
```
error - not a setting instance
line 1545 of /lib/adminlib.php: call to debugging()
line 95 of /theme/telaformation/settings/footer.php: call to admin_settingpage->add()
line 117 of /theme/telaformation/settings.php: call to include()
line 57 of /admin/settings/appearance.php: call to include()
line 8670 of /lib/adminlib.php: call to require()
line 26 of /admin/search.php: call to admin_get_root()
```

Dig up this issue, somehow I can't reproduce it locally and I can't reproduce it on the internal test platform either.

Note : However, it seems that the options of the footer are correctly taken into account ...

**Comment by kstefanini** [comment]
Error comes from settings name theme_telaformation is redundant here https://github.com/telabotanica/moodle-theme_telaformation/blob/dev/settings/footer.php#L77
This name is already used here https://github.com/telabotanica/moodle-theme_telaformation/blob/dev/settings/footer.php#L36

I tried modify settings name line 77 from `theme_telaformation` to `theme_telaformation_fix`, and it fixes the error

Source: https://tracker.moodle.org/browse/MDL-19942

**Comment by CrymSonir** [comment]
Link to this commit : https://github.com/telabotanica/moodle-theme_telaformation/commit/f9f3247c2020f9e2c53bb0970ba0b7da5ec20376

**Comment by kstefanini** [comment]
But it seems `$setting` created line 74 is never used anymore

**Comment by CrymSonir** [comment]
Yes $setting is only used to populate $page using the different function from simple_theme_settings object.

If u prefer call this :
`$setting->add_headings ('footercolumn', $ i);`

Is like doing this :
```
$setting = new admin_setting_heading(
                $name,
                $title,
                $description
        );
 $setting->set_updatedcallback('theme_reset_all_caches');
 $page->add($setting);
```

**Comment by kstefanini** [comment]
Oh right, thanks for the explanation!
