### ISSUE TITLE
Créer deux classes pour les éléments du footer

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#17]
I wish to have new classes for elements in the footer. 
With classes i will be able to add style to these elements in the custom css thing.

Today the titles and elements in the footer have the same class "txt_to_html"

![Capture d’écran de 2021-01-08 14-33-11](https://user-images.githubusercontent.com/22638189/104022534-b2c8b200-51c0-11eb-9b7c-d90fb854b227.png)

Il faudrait créer 2 class , une footer_title pour le premier élément et une footer_item  pour son élément enfant (en fait j'vois pas trop pourquoi écrire en anglais ici)

**Comment by CrymSonir** [comment]
Addition of two selector id to be able to target the elements of the footer '#footerheadingX' and '#footertextX' where X is the number of the concerned column.

Deploy with : https://github.com/telabotanica/moodle-theme_telaformation/pull/18

PS : On avait fait le choix d'utiliser l'anglais pour faciliter la compréhension de l'historique du plugin dans le cas ou certaines personnes serait intéressé pour partager des améliorations. Sinon c'est comme vous préférez :)
