### ISSUE TITLE
Page de connexion

### ISSUE THREAD

**Issue by CrymSonir** [telabotanica/moodle-theme_telaformation#2]
- [x] Refonte template
- [x] Faire valider design -> Proposition 2
- [x] Agrandir la box login en largeur
- [x] Améliorer box de texte au dessus et dessous du login
- [x] Agrandir box signup
- [x] Améliorer rendu background

Proposition 2 :
<img width="1437" alt="proposition 2" src="https://user-images.githubusercontent.com/8981947/95749934-abb30600-0c9c-11eb-97dc-564d6905c4bc.png">

Mise en page basique avec formulaire simple en milieu de page sur fond blanc.

**Comment by CrymSonir** [comment]
Proposition 1 : 
![proposition 1](https://user-images.githubusercontent.com/8981947/95749234-8ffb3000-0c9b-11eb-9373-72ccb4032ad5.png)

Un élément à gauche sur fond de couleur contenant les informations nécessaires pour s'authentifier et une image à droite modifiable dans les options du thème.

Proposition 2 :
<img width="1437" alt="proposition 2" src="https://user-images.githubusercontent.com/8981947/95749934-abb30600-0c9c-11eb-97dc-564d6905c4bc.png">

Mise en page basique avec formulaire simple en milieu de page sur fond blanc.

Proposition 3: 
<img width="725" alt="proposition 3" src="https://user-images.githubusercontent.com/8981947/95750392-5aefdd00-0c9d-11eb-9159-2cfc528cd332.png">

même chose que la proposition 2 mais avec un image en arrière plan modifiable dans les options du thème.

**Comment by verovs** [comment]
@CrymSonir je fais faire un vote à mes collégues et j'te note ça ici

**Comment by verovs** [comment]
La 2, basique :)

**Comment by CrymSonir** [comment]
@verovs Okay c'est noté on retient donc la Proposition 2

**Comment by CrymSonir** [comment]
Retour :

- [ ] Agrandir la boxe login en largeur
- [ ] Améliorer box de texte au dessus et dessous du login
