### ISSUE TITLE
[homepage] carousel img not in full width

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#20]
- browser Firefox 84.0.2 (64 bits)

On the homepage : https://mooc-test.tela-botanica.org/?redirect=0
The carousel images aren't display in full width. 
They only appears in full width when they slide

Not in full width : carousel-item active, carousel-item 
![Capture d’écran de 2021-01-12 12-56-23](https://user-images.githubusercontent.com/22638189/104311677-d4ce7700-54d5-11eb-8240-df1ee29457f9.png)

In full width when they are sliding : carousel item-next, item-left

![Capture d’écran de 2021-01-12 12-49-14](https://user-images.githubusercontent.com/22638189/104311841-152df500-54d6-11eb-8cfe-0ae262dabfbd.png)

The comportment is the same logged in or not

**Comment by CrymSonir** [comment]
This issue was fixed with the latest version deployed.

See merged PR : https://github.com/telabotanica/moodle-theme_telaformation/pull/24
