### ISSUE TITLE
Warnings on database type when uploading a plugin

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#21]
I uploaded a plugin on the staging and got a screen with cheking stuff
In these stuffs I got 2 warnings
One on the utf format which  I want to keep despite what the warning said (idc about emoji)
One I don't understand at all : "Votre base de données comporte des tables qui utilisent le format de fichier Antelope. Il vous est vivement recommandé de convertir les tables au format de fichier Barracuda. "
what does that means @CrymSonir ? We care about this stuff? we want barracuda? ^^ 

![Capture d’écran de 2021-01-20 11-01-24](https://user-images.githubusercontent.com/22638189/105159134-07e4bc00-5b0f-11eb-9c24-e9dc3e74c10b.png)

**Comment by CrymSonir** [comment]
I will look at this next week.

It's just a warning so it shouldn't bother, but it's better to follow their instructions.

**Comment by CrymSonir** [comment]
I solved the problem, some information about what I did.

On server side go to moodle directory.

Fixed warning mysql_full_unicode_support :
** Run `php admin/cli/mysql_collation.php --collation=utf8mb4_unicode_ci`

Fixed warning unsupported_db_table_row_format:
Most of the time this error is related to the one mentioned above. This was the case here.
But in case this command will help to fix this : `php admin/cli/mysql_compressed_rows.php`
