### ISSUE TITLE
On every "activity" content type of courses > warning of "mustache lib"

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#22]
on the staging,
tested on MOOC TVB & MOOC bota 2020
On every pages (content type of moodle) and quizzes  (didnt checked the others types) i go i got big warning about " mustache lib " before the actual content
It begins with :  
line 76 of /lib/classes/output/mustache_string_helper.php: call to get_string()
line ? of unknownfile: call to core\output\mustache_string_helper->str()
line 82 of /lib/classes/output/mustache_helper_collection.php: call to call_user_func()
![Capture d’écran de 2021-01-20 11-49-20](https://user-images.githubusercontent.com/22638189/105164559-8f352e00-5b15-11eb-90ac-cbcc3fda9ea4.png)

test link :  

- https://mooc-test.tela-botanica.org/mod/page/view.php?id=1273
- https://mooc-test.tela-botanica.org/mod/page/view.php?id=3161
- https://mooc-test.tela-botanica.org/mod/page/view.php?id=3150

**Comment by CrymSonir** [comment]
It's linked to the ticket : https://github.com/telabotanica/moodle-theme_telaformation/issues/19

When there are missing translations it displays this kind of error.

**Comment by verovs** [comment]
thanks! Im clossing this one to not have doublons
