### ISSUE TITLE
header modif'

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#23]
we need to : 

- [x] - change the logo
- [x] - change the nav color to white
- [x] - delete the display of the site name (cause the logo is sooo big)

->I didnt find any of those parameters :'(  
-> I  only changed the color of the header and the favicon
- here is the logo i got : https://mooc.tela-botanica.org/pluginfile.php/1/theme_moockie/sitelogo/1604069728/logo_telaformation%28101px%29.png

**Comment by verovs** [comment]
I found the logo parameter  & color (needed to put 3 F and not 5 oO ) :)

**Comment by CrymSonir** [comment]
> I found the logo parameter & color (needed to put 3 F and not 5 oO ) :)

Yes the color settings only work with a 3 or 6 value format.

Example: #FFF or #FFFFFF

About the color of the hamburger you should be able to change its color or design via the option:
Raw SCSS
theme_telaformation | scss
In the advanced option tab.

Otherwise we can consider adding options to define the background and text color of the hamburger via the theme options, as you want :)

Regarding the name of the site, you can hide it via the raw sccs option that I indicated to you previously or if you wish I delete it permanently from the code.

**Comment by verovs** [comment]
thank you! i will try to do that :)

**Comment by verovs** [comment]
Soooo.. I tried to add a scss in the scss thing and every single modification of color I did before went away >< 


I'm not sure if my syntaxe and scss is ok but i didnt think it will broke every parameters stuff
The things that I think it changes: 
theme_telaformation > general options > colors things & font & nav bar color things


before :   
![Capture d’écran de 2021-01-26 16-57-08](https://user-images.githubusercontent.com/22638189/105869869-ffe9b800-5ff7-11eb-94cf-479ec3783cc1.png)


and after saving my attempt of scss
![Capture d’écran de 2021-01-26 17-09-09](https://user-images.githubusercontent.com/22638189/105871237-67543780-5ff9-11eb-919b-c0ce02d38734.png)

note: every parameters  (options colors etc. ) are still  right answered in the backoffice, just they are not display anymore

screen of culprit scss
![Capture d’écran de 2021-01-26 17-01-24](https://user-images.githubusercontent.com/22638189/105871322-7935da80-5ff9-11eb-9ba7-b62f99a1ae7b.png)

link of the culprit scss : https://mooc-test.tela-botanica.org/admin/settings.php?section=themesettingtelaformation#theme_telaformation_advanced 

sorry :'(

**Comment by clementpr** [comment]
A single small error in the custom style will block the generation of the site style. Hence the rendering. It would be necessary to correct the scss, see example on the site.

**Comment by CrymSonir** [comment]
> Soooo.. I tried to add a scss in the scss thing and every single modification of color I did before went away ><
> 
> I'm not sure if my syntaxe and scss is ok but i didnt think it will broke every parameters stuff
> The things that I think it changes:
> theme_telaformation > general options > colors things & font & nav bar color things
> 
> before :
> ![Capture d’écran de 2021-01-26 16-57-08](https://user-images.githubusercontent.com/22638189/105869869-ffe9b800-5ff7-11eb-94cf-479ec3783cc1.png)
> 
> and after saving my attempt of scss
> ![Capture d’écran de 2021-01-26 17-09-09](https://user-images.githubusercontent.com/22638189/105871237-67543780-5ff9-11eb-919b-c0ce02d38734.png)
> 
> note: every parameters (options colors etc. ) are still right answered in the backoffice, just they are not display anymore
> 
> screen of culprit scss
> ![Capture d’écran de 2021-01-26 17-01-24](https://user-images.githubusercontent.com/22638189/105871322-7935da80-5ff9-11eb-9ba7-b62f99a1ae7b.png)
> 
> link of the culprit scss : https://mooc-test.tela-botanica.org/admin/settings.php?section=themesettingtelaformation#theme_telaformation_advanced
> 
> sorry :'(


Indeed concerning this option you should know that the slightest syntax error in the field will crash the moodle script responsible for compiling the scss files.

Regarding your piece of code, if I'm not wrong the correct syntax would be more like this:
`
[………]
                &:hover {
                    color: darken(#009FB8, 80%);
                }
[………]
`

**Comment by verovs** [comment]
thank you!

**Comment by verovs** [comment]
thank you for rewritting the css. but it still doesnt work :s    (but it doesnt crash the website al least^^)
And i tried to hide the site name with css but didnt succeed.

could you please :  
make the inside of the burger (the 3 lines) in blue & darken on hover
hide the site name

Morevover, it seems, and i dont know where i edited that, i changed the hover txt color on action button to orange and i dont want that,  the 'action button' are like "save change / upload img "
and i changed also the hover txt color of nav item in darkred  
Do you know where are these settings that i cant find anymore ?

**Comment by verovs** [comment]
hey @CrymSonir :)
Could you please hide the site name before we will move to production?

**Comment by CrymSonir** [comment]
Done by CSS
