### ISSUE TITLE
setting question

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#27]
I cant find a way to display block in the homepage : i dont have / cant find an edit type action 

ie " Important : after making the changes, go to the homepage of your site to add content using blocks. You can find the homepage here : Homepage."

**Comment by CrymSonir** [comment]
To activate the edit mode of the homepage.

You have to go to the dashboard, activate the edit mode, then return to the homepage.

**Comment by verovs** [comment]
thanks!
I keep this ticket open if you don't mind for "easy to find" info :)
