### ISSUE TITLE
[course] Add access restriction on section

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#31]
I dunno if its a bug or just a missing feature we didn't specify we needed but we really need that.
We need to restrict access at section (and not just activities), ie: display only S1 if date is after 3/3/21, display only if questionnaire-activity is submit etc..
On the staging we don't have this parameters, we only have these parameters inside a section, for an activity-type.
It not seems to be dependable of the course format because I tested it with several and it never was display

It only displays the title "Resteindre l'accès" but nothing under it  :'(  

![Capture d’écran de 2021-02-17 11-36-27](https://user-images.githubusercontent.com/22638189/108192375-7881f700-7114-11eb-981b-64c72889a29d.png)

here is the test course : https://mooc-test.tela-botanica.org/course/view.php?id=23
here is one section edit link: https://mooc-test.tela-botanica.org/course/editsection.php?id=268&sr=1

**Comment by CrymSonir** [comment]
This is a bug that I saw and fixed yesterday, the fix is ​​not yet deployed. I will close the issue when the patch is deployed :)

The JS code goes into a mess due to an unhandled condition on this type of page.
