### ISSUE TITLE
profil "by default" is a blank screen

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#36]
I wanted to see if i needed to do some changments on this one but the content is just a blank screen and an empty div

link on test (but prod is same) :  https://mooc-test.tela-botanica.org/user/profilesys.php (found on admin site > presentation > profil par defaut)

and screen

![Capture d’écran de 2021-04-20 17-07-33_cut](https://user-images.githubusercontent.com/22638189/115421311-20db3700-a1fc-11eb-844e-70e30d741713.png)

**Comment by CrymSonir** [comment]
Fix deployed with the latest version of the plugin.

**Comment by verovs** [comment]
It is deployed on prod but I only have breadcrumb on display. I was hoping to see actual profil (like for  the dashboard). but i checked in our moodle36 and it's the same. weird stuff. sorry for making you fixed this! thank you!

**Comment by CrymSonir** [comment]
Yes I noticed the same behavior on boost as well, I don't know if it's a will on their part or a bug on the moodle side.
