### ISSUE TITLE
How to hide type (activity/ressources) icons?

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#43]
I dont want these icons to show in my course display.
is there a way to hide them? I don't find it

Im' talking about these icons (on the left of the screenshot):
![Capture d’écran de 2021-04-23 11-46-31](https://user-images.githubusercontent.com/22638189/115853921-fcfd3880-a429-11eb-83a4-9d3d26c005db.png)
here are the activity icon: https://libraryguides.ambs.edu/c.php?g=236215&p=1568334 

Is it from the course format or is it something on core moodle?

**Comment by verovs** [comment]
seems to be in course format
but no is checked and i still see it. Will need to see with a student role if he saws it
![Capture d’écran de 2021-04-23 14-58-18](https://user-images.githubusercontent.com/22638189/115874448-65591380-a444-11eb-9790-2990a48f67ee.png)

-> no it's not working, student still see it

**Comment by CrymSonir** [comment]
I think there should be a way to hide these icons by modifying the css.

**Comment by verovs** [comment]
yeah my stuff is not working : course format : non

**Comment by verovs** [comment]
> I think there should be a way to hide these icons by modifying the css.

Will need to do it in the custom css box ?

**Comment by CrymSonir** [comment]
Yea just there : [https://mooc.tela-botanica.org/admin/settings.php?section=themesettingtelaformation#theme_telaformation_advanced](https://mooc.tela-botanica.org/admin/settings.php?section=themesettingtelaformation#theme_telaformation_advanced)

But beware the slightest indentation / syntax error will cause the css to skip :)

Be careful to also have a sufficiently precise selector under penalty of hiding any icons on the entire platform.

**Comment by verovs** [comment]
thank you! will try it on test ^^

**Comment by verovs** [comment]
got it working! with
```
 .iconlarge.activityicon {
display: none
}
```
thank you so much
