### ISSUE TITLE
on homepage, on "general" section, "slipped deposited" is'nt working

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#45]
on home, on "general" section  (= the section before course list, where we can add site activities/resources/pages), "slipped deposited"(= translate for glissé/déposé) is'nt working. I can't move activities items.
I can "grab" them, by the icon, but can't drop them inside the section
example: moving "newsletter test" after "elements cachés"

![Capture d’écran de 2021-04-27 15-08-52](https://user-images.githubusercontent.com/22638189/116247451-2b04b480-a76b-11eb-8d20-d27827142a37.png)

**Comment by CrymSonir** [comment]
Can you give me the link to the course?

**Comment by verovs** [comment]
that's not a course, that's the site activities, on homepage (in edition mode) : https://mooc.tela-botanica.org/?redirect=0  

screen:
![Capture d’écran de 2021-04-27 16-09-25](https://user-images.githubusercontent.com/22638189/116256238-4c699e80-a773-11eb-9861-1b5087156ebf.png)

**Comment by CrymSonir** [comment]
Okay the operation on this page is different, you have to click on the icon then click on the place where you want to place your element.

**Comment by verovs** [comment]
oooooooh
thank you !!
