### ISSUE TITLE
the "connexion" button isn't always showing on navigation

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#46]
sometimes we can see a button in place of "you are note connected" in the nav header on the homepage and sometimes it's not showing (on homepage and on every others pages type)

_screen where we see the button class_
![Capture d’écran de 2021-04-27 17-31-14](https://user-images.githubusercontent.com/22638189/116269578-a459d280-a77e-11eb-9fb4-f62d019e0135.png)

_screen where there is no button class_

![Capture d’écran de 2021-04-27 17-31-49](https://user-images.githubusercontent.com/22638189/116269778-c8b5af00-a77e-11eb-86d3-55ab55411c13.png)

**Comment by CrymSonir** [comment]
On the second screen you were logged in as a guest so the button is not displayed.

**Comment by verovs** [comment]
oh wow would have never think of that
