### ISSUE TITLE
Page profil et page préférence

### ISSUE THREAD

**Issue by CrymSonir** [telabotanica/moodle-theme_telaformation#5]
- [x] Refonte du template 
- [x] Faire valider le design -> Proposition 3
Proposition 3:

**Page profile**
Toutes les informations sur une seul page :
![image](https://user-images.githubusercontent.com/8981947/95753826-727d9480-0ca2-11eb-8ec1-7c79dc1038cc.png)

**Page de préf**
![Proposition 3 pref](https://user-images.githubusercontent.com/8981947/95753946-9fca4280-0ca2-11eb-8f3c-1f2d01f852e7.png)

**Comment by CrymSonir** [comment]
Proposition 1:

**Page profile**
Onglet 1 : des info sur l'utilisateur
![Proposition 1 profile](https://user-images.githubusercontent.com/8981947/95752325-23cefb00-0ca0-11eb-9094-00c7d820f233.png)
Onglet 2 : On retrouve "mes cours"
![Proposition 1 profile 2](https://user-images.githubusercontent.com/8981947/95752606-8de7a000-0ca0-11eb-9053-5333ce96844d.png)
Onglet 3 : Le reste des informations/liens de la page profile
![Proposition 1 profile 3](https://user-images.githubusercontent.com/8981947/95752570-7e685700-0ca0-11eb-95a7-f4260041c661.png)
Note : le dernier onglet serait un lien vers la page d'édition du profile

**Page de préf**
![Proposition 1 pref](https://user-images.githubusercontent.com/8981947/95752333-27628200-0ca0-11eb-8c2f-281c0ed35ed0.png)


Proposition 2:

**Page profile**
Onglet 1: On retrouve "mes cours"
![Proposition 2 profile 1](https://user-images.githubusercontent.com/8981947/95752993-3269e200-0ca1-11eb-8ee1-c34dcd072af4.png)
Onglet 2: Le reste des informations/liens de la page profile
![Proposition 2 profile 2](https://user-images.githubusercontent.com/8981947/95753019-3f86d100-0ca1-11eb-8d93-b90e92fde8eb.png)

**Page de préf**
![Proposition 2 pref](https://user-images.githubusercontent.com/8981947/95753741-51b53f00-0ca2-11eb-9eb1-5ecec4e5cc94.png)

Proposition 3:

**Page profile**
Toutes les informations sur une seul page :
![image](https://user-images.githubusercontent.com/8981947/95753826-727d9480-0ca2-11eb-8ec1-7c79dc1038cc.png)

**Page de préf**
![Proposition 3 pref](https://user-images.githubusercontent.com/8981947/95753946-9fca4280-0ca2-11eb-8f3c-1f2d01f852e7.png)

**Comment by verovs** [comment]
On reste sur la proposition 3 @CrymSonir

**Comment by CrymSonir** [comment]
@verovs Okay on retient donc la proposition 3 :)
