### ISSUE TITLE
Design material

### ISSUE THREAD

**Issue by verovs** [telabotanica/moodle-theme_telaformation#7]
I don't have any right on the project board :'(

We are looking at the material design and will come back to you (@CrymSonir )
We have a brand style guide mostly for color tho.
It's the association styleguide but for the telaformation we seems to use the complementary color aka blue & violet : https://drive.google.com/file/d/15506IoxaH1_Y_WwpavuGiolbDIE7N0_E/view?usp=sharing

**Comment by verovs** [comment]
voici le material design qu'on préfère : https://byrushan.com/projects/material-admin/app/2.6/index.html

**Comment by CrymSonir** [comment]
@verovs Okay this is noted for the general design.

Also I have deployed a bunch of fixes regarding the login page you can see the changes now.

**Comment by verovs** [comment]
thanks! your picture is way nicer than my test screenshot ^^
